### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by 0999312** [0999312/SlashBlade_Resharped#1]
首发版本测试前需要完成：

- [x] 重写所有的注册相关代码（物品、合成等）
- [x] 调整部分特性
- [x] 配置文件
- [x] 自定义按键
- [x] 自定义拔刀剑接口
- [x] 合成表调整
- [x] 基于标签的可攻击实体的黑名单

**Comment by 0999312** [comment]
调整特性内容：

- [ ] 重新添加耀魂值代替原有的经验值消耗
- [ ] 耀魂碎片的掉落机制修改
- [ ] 刀剑类型显示以及数据处理
- [ ] ToolTip 样式处理
- [ ] 评级攻击力加成回归初代
- [ ] 木偶等刀独立物品处理，断刀机制取消与NBT的关联
- [ ] 鞘的稳定实现（避免出现使用鞘进行攻击的情况）

**Comment by 0999312** [comment]
新一轮TODO List：  
- [ ] SE（Special Effect）机制
- [ ] 超SA，以及超SA的触发机制
- [ ] 幻影刃
- [ ] 暮色联动（夜叉、鄂门）
- [ ] 露台（Simply Sword联动）
- [ ] 银纸竹光->万变之鞘机制（看情况考虑）
- [ ] 红玉、狐月刀合成调整
- [ ] 枯石太刀
- [ ] 刀挂台附魔机制
